### PR TITLE
Integration of AnalyticsHttpClientBuilderService into External IdPClient

### PR DESCRIPTION
**Pull request by Niveathika92**
## Purpose
Integration of AnalyticsHttpClientBuilderService into External IdPClient to use a common HTTP client 

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

**Comment by suhothayan** [comment]
@Niveathika92 whats the status of this?

**Comment by Niveathika92** [comment]
This will solve the initial issue but an improvement to product-sp is identified, https://github.com/wso2/product-sp/issues/456, to revisit all HTTP client behaviours. We can merge after the improvement is fully finalized since behaviour may change.

**Comment by mohanvive** [comment]
@Niveathika92 , Can we create a separate branch and maintain the changes in that until fixes are finalized?

**Comment by mohanvive** [comment]
@Niveathika92 , I have moved the fixes to hostname-verify-fix branch. Please keep the branch updated. We can merge the branch into master once other fixes are finalized.

**Pull request closed without merging**
