### PR TITLE
Allow Attributes with OBJECT type

### PR DESCRIPTION
**Pull request by icholy**

### CODE REVIEW

**Comment by icholy** [comment]
@mohanvive hey, can I get some feedback on this?

**Comment by mohanvive** [comment]
@icholy , Thanks for the PR.. And appreciate your contribution for the open-source community.. I have gone through the changes that you have provided.. It provides Object support for the stream but the fix is partial.. This will break the consistency of supported data types throughout the server/platform. We need to fix some more components to make it clean and work.. For example : org.wso2.carbon.databridge.receiver.thrift  , org.wso2.carbon.event.receiver.core and etc.. Importantly we need to regenerate the thrift server java code with updated changes.. Will provide the detailed explanation by Tomorrow on possible solutions ..

**Comment by icholy** [comment]
@mohanvive thanks for looking into it :)

Here's my use case: I'm coming from esper, and I want to have attributes that are instances of my own classes. I intend to write functions/aggregates/receivers/publishers that know how to work with them.

**Comment by icholy** [comment]
Another option is to allow a `with` tag in the attribute mapping. Allow users to register attribute mapping functions. But I looked through the code and it looks like this would require a lot of code change.

``` xml
<eventReceiver ... xmlns="http://wso2.org/carbon/eventreceiver">
    <from ... />
    <mapping customMapping="enable" type="wso2event">
        <from streamName="sensor.stream" version="1.0.6"/>
        <property>
            <from dataType="meta" name="time"/>
            <to name="meta_timestamp" type="Object"/>
            <with name="timestampToDateObject" />
        </property>
        <property>
            <from dataType="meta" name="meta_name"/>
            <to name="meta_name" type="string"/>
            <with name="toUpperCase"/>
        </property>
    </mapping>
    <to ... />
</eventReceiver>
```

**Comment by icholy** [comment]
If there's an `OBJECT` attribute, it fails when generating a sample event.

```
[2016-05-03 14:49:06,949] ERROR {org.apache.catalina.core.StandardWrapperValve} -  Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception
java.io.IOException: An exception occurred processing JSP page /eventstream/getSampleEvent_ajaxprocessor.jsp at line 26

23:     String responseText = "";
24: 
25:     if (streamId != null && eventType != null) {
26:         String sampleEvent = stub.generateSampleEvent(streamId, eventType);
27:         if (sampleEvent != null) {
28:             responseText = sampleEvent;
29:         }


Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:460)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.CSRFPreventionFilter.doFilter(CSRFPreventionFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.CRLFPreventionFilter.doFilter(CRLFPreventionFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1698)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.axis2.AxisFault: empty String
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:370)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:445)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.event.stream.stub.EventStreamAdminServiceStub.generateSampleEvent(EventStreamAdminServiceStub.java:3244)
	at org.apache.jsp.eventstream.getSampleEvent_005fajaxprocessor_jsp._jspService(getSampleEvent_005fajaxprocessor_jsp.java:76)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	... 50 more 
```

The problem is here: https://github.com/wso2/carbon-analytics-common/blob/48ce4938b4bcbc71870dc947ac5e65aa0d0c084a/components/event-stream/org.wso2.carbon.event.stream.core/src/main/java/org/wso2/carbon/event/stream/core/internal/util/SampleEventGenerator.java#L152-L165

**Comment by mohanvive** [comment]
@icholy , Sorry for not getting back to you early.. I am still evaluating possible options to achieve this..  And also, I am planning to initiate a discussion on this since this will affect major area of WSO2 CEP server.. So far when moving from Esper to Siddhi, we are avoided using Object data types and only used primitive data types (Because primitive data types helps to gain more performance eventually) .. Will get back to you asap on this (about our standpoint on supporting this)...

**Comment by icholy** [comment]
@mohanvive no worries. The reason I started with all of this is because the [Siddhi README](https://github.com/wso2/siddhi/blob/7de0339791cbd6a7e03066942ec7eb466a95d079/README.md) states that.

> Attributes supported are: boolean, string, int, long, float, double, object

It seems like writing a producer that uses the `MapInputMapper` is the easiest way to get what I want. I understand that some features (like publishers) won't work with events which have object attributes, but I'm ok with that.

**Comment by icholy** [comment]
How about just enforcing all Objects to implement `java.io.Serializable` ?

**Comment by icholy** [comment]
@mohanvive any word on this?

**Comment by mohanvive** [comment]
Yes Icholy, I have discussed about this internally.. We are planning to add "Object" support to CEP roadmap (Siddhi level support is already there) but couldn't guarantee on any timelines.. Anyway, below is the plan.. As the initial step, send object as serializable (String attribute type) in to CEP and in Siddhi level deserialize to process them. When sending out from Siddhi, serialize again.. Here to serialize and deserialize at Siddhi level, we need two custom extension.. And also we may need some improvements/extension to Siddhi to access object methods.. If this works, afterwards we are planning to incorporate Object support at transport level.. 

@suhothayan , FYR

**Comment by jcechace** [comment]
@mohanvive Hello Mohan, do you have any update on this? Did the object type support make it to the roadmap? We are currently evaluating WSO2 CEP and complex types (especially array support) is something we are missing.

**Comment by mohanvive** [comment]
Siddhi which is the Processing engine of  WSO2 CEP have Object support but other components like Input Mapper does not have support for Object. Here you can achieve this use case with the help of Map extension [1] as of now. Next version fo CEP (which is restructured as DAS 4.0.0) contains some design changes which provides the facility to write your own Input and Output Mapper. You can achieve your use case by writing an Object Input Mapper in next release.  

[1] https://docs.wso2.com/display/CEP420/Sample+0120+-+Using+the+Map+Extension

**Pull request closed without merging**
