### PR TITLE
Upgrade thrift from 0.9.2 to 0.16.0

### PR DESCRIPTION
**Pull request by hwupathum**
$subject

### Related issues
- https://github.com/wso2/product-is/issues/15407

Necessary Java files have been generated using the thrift complier

### CODE REVIEW

**Review by tishan89 — APPROVED** [review]

**Comment by tishan89** [comment]
Approved the changes. But please do proper E2E testing before merging as this changes most of the generated code which is in the core. Databridge thrift connection should be test extensively.

**Comment by hwupathum** [comment]
Local integration tests were run and were successful

**Comment by npamudika** [comment]
Fixes related to wso2/api-manager#1252

**Comment by hwupathum** [comment]
Tested with identity-analytics according to the documentation https://is.docs.wso2.com/en/5.11.0/learn/configuring-identity-analytics/#enable-analytics

**Review by ashensw — APPROVED** [review]

**Review by tishan89 — APPROVED** [review]

**Pull request merged**
